# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-31917-H370HD3/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/aokim/RockWave/SYNTH/Zedboard/Zedboard.cache/wt [current_project]
set_property parent.project_path /home/aokim/RockWave/SYNTH/Zedboard/Zedboard.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo /home/aokim/RockWave/SYNTH/Zedboard/Zedboard.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property generic Xilinx [current_fileset]
add_files /home/aokim/RockWave/fw/night.coe
read_verilog /home/aokim/RockWave/HDL_SRC/CORE/core_general.vh
read_verilog -library xil_defaultlib {
  /home/aokim/RockWave/HDL_SRC/CORE/Execute/alu.v
  /home/aokim/RockWave/HDL_SRC/CORE/Execute/comp.v
  /home/aokim/RockWave/HDL_SRC/Board_Common/dfilter.v
  /home/aokim/RockWave/HDL_SRC/Peripheral/GPIO/fnc_gpio.v
  /home/aokim/RockWave/HDL_SRC/CORE/instruction_decode/instruction_decode.v
  /home/aokim/RockWave/HDL_SRC/Peripheral/LocalBus/localbus.v
  /home/aokim/RockWave/HDL_SRC/CORE/instruction_decode/obuf.v
  /home/aokim/RockWave/HDL_SRC/CORE/MemoryAccess/ram.v
  /home/aokim/RockWave/HDL_SRC/Board_Common/refclk.v
  /home/aokim/RockWave/HDL_SRC/Peripheral/GPIO/reg_gpio.v
  /home/aokim/RockWave/HDL_SRC/Board_Common/reg_ronly.v
  /home/aokim/RockWave/HDL_SRC/Board_Common/reg_rw.v
  /home/aokim/RockWave/HDL_SRC/CORE/RegisterFile/register.v
  /home/aokim/RockWave/HDL_SRC/CORE/RegisterFile/register_file.v
  /home/aokim/RockWave/HDL_SRC/CORE/Fetch/rom.v
  /home/aokim/RockWave/HDL_SRC/CORE/StateMachine/statemachine.v
  /home/aokim/RockWave/HDL_SRC/Board_Common/synchronizer.v
  /home/aokim/RockWave/HDL_SRC/CORE/_top/top_core.v
  /home/aokim/RockWave/HDL_SRC/CORE/Execute/top_execute.v
  /home/aokim/RockWave/HDL_SRC/CORE/Fetch/top_fetch.v
  /home/aokim/RockWave/HDL_SRC/Peripheral/GPIO/top_gpio.v
  /home/aokim/RockWave/HDL_SRC/CORE/MemoryAccess/top_memoryaccess.v
  /home/aokim/RockWave/HDL_SRC/CORE/WriteBack/writeback.v
  /home/aokim/RockWave/SYNTH/Zedboard/top_zedboard.v
}
read_ip -quiet /home/aokim/RockWave/SYNTH/Zedboard/Zedboard.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/aokim/RockWave/SYNTH/Zedboard/Zedboard.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/aokim/RockWave/SYNTH/Zedboard/Zedboard.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files /home/aokim/RockWave/SYNTH/Zedboard/Zedboard.srcs/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_zedboard -part xc7z020clg484-1 -verilog_define INST_ROM_FILE_NAME=rv32ui-p-add.hex


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_zedboard.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_zedboard_utilization_synth.rpt -pb top_zedboard_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
